{% set name = "pyCycle" %}
{% set version = "4.4.0" %}
{% set sha256 = "a10aae9e5ca01e317237f41a0f657d977ea9bf8dd938a1289fdfca9919adcf9a" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/om_pycycle/om_pycycle-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - openmdao >=3.10.0
    - python >={{ python_min }}

test:
  requires:
    - testflo >=1.3.6
    - pip
    - python {{ python_min }}
  imports:
    - pycycle
  commands:
    - python -m pip check

about:
  home: https://github.com/OpenMDAO/pyCycle
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A thermodynamic cycle modeling library.
  description: |
    A thermodynamic cycle modeling library, designed primarily to model jet engine performance.
    It is built on top of the OpenMDAO framework and the design is heavily inspired by NASA's NPSS software.
    You need to be at least familiar with either OpenMDAO or NPSS in order to be successful in using this library.
  doc_url: https://www.mdpi.com/2226-4310/6/8/87/pdf
  dev_url: https://github.com/OpenMDAO/pyCycle
  doc_source_url: https://github.com/OpenMDAO/pyCycle/tree/master/pycycle/docs

extra:
  recipe-maintainers:
    - robfalck
    - swryan
    - sanbales
